version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: webflux
#      MONGO_INITDB_ROOT_PASSWORD: webflux
  #    volumes:
  #      - ./data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo