version: "3.1"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./webflux_data:/var/lib/postgresql
      - ./db-init-scripts/initdb.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  webflux_data: