version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./webflux_data:/var/lib/postgresql/datango
volumes:
  webflux_data: