spring:
  data:
    mongodb:
      uri: mongodb+srv://mongo:mongo@cluster0.cz90e.mongodb.net/db_music?retryWrites=true&w=majority
#      database: db_music

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
