CREATE SCHEMA MUSIC;

CREATE TABLE IF NOT EXISTS MUSIC.MUSIC
(
    ID   SERIAL PRIMARY KEY,
    NAME varchar(64) NOT NULL,
    ARTIST varchar(32) NOT NULL
);

INSERT INTO MUSIC.MUSIC(name, artist)
VALUES ('HEARTS ON FIRE', 'HAMMERFALL');

INSERT INTO MUSIC.MUSIC(name, artist)
VALUES ('RAINING BLOOD', 'SLAYER');

INSERT INTO MUSIC.MUSIC(name, artist)
VALUES ('ROCK YOU LIKE A HURRICANE', 'SCORPIONS');

INSERT INTO MUSIC.MUSIC(name, artist)
VALUES ('THE FOUR HORSEMEN', 'METALLICA');

INSERT INTO MUSIC.MUSIC(name, artist)
VALUES ('EVEN FLOW', 'PEARL JAM');